using UnityEngine;

namespace Example.States
{
    /// <summary>
    /// This is an automatically generated script that is created ONCE and extends from the autogenerated code from, ScriptableStateController
    /// </summary>
    [AddComponentMenu("States/State Machine")]
    public class StateMachineController : BaseStateMachineController
    {

        protected override void Start()
        {
            base.Start();
        }

        protected override void Update()
        {
            base.Update();
        }

        protected override void OnDrawGizmos()
        {
            base.OnDrawGizmos();
        }
    }
}