namespace Example.States
{
    /// <summary>
    /// This is an automatically generated script that is created ONCE and extends from the autogenerated code from, ScriptableStateController
    /// </summary>
    public class NewScriptableStateControllerController : BaseNewScriptableStateControllerController
    {

        protected override void Awake()
        {
            base.Awake();
        }

        protected override void Update()
        {
            base.Update();
        }

        protected override void OnDrawGizmos()
        {
            base.OnDrawGizmos();
        }
    }
}