namespace SNAMESPACE_ENTRY
{
    /// <summary>
    /// This is an automatically generated script that is created ONCE and extends from the autogenerated code from, ScriptableStateController
    /// </summary>
    public class SSTATECONTROLLER_ENTRY : BASE_SSTATECONTROLLER_ENTRY
    {

        protected override void Awake()
        {
            base.Awake();
        }

        protected override void Update()
        {
            base.Update();
        }

        protected override void OnDrawGizmos()
        {
            base.OnDrawGizmos();
        }
    }
}